import json
import os
from typing import ClassVar, Final

from dotenv import load_dotenv
from pydantic import BaseModel

load_dotenv()

class Config(BaseModel):
    DEFAULT_LOGGING_PATH: Final[str] = os.getenv('DEFAULT_LOGGING_PATH', "/var/log/slack-bot-server")
    TEMP_FILE_PATH: Final[str] = os.getenv('TMP_FILE_PATH', "")  # 임시 파일 저장 경로
    DEFAULT_LOGGING_LEVEL: Final[str] = os.getenv('DEFAULT_LOGGING_LEVEL', "DEBUG")

    # Redis
    REDIS: ClassVar[dict] = json.loads(os.getenv("REDIS", "{}"))
    REDIS_HOST: str = REDIS.get("host", "")
    REDIS_PORT: int = REDIS.get("port", 6379)
    REDIS_PASSWORD: str = REDIS.get("password", "")
    REDIS_DB: int = int(os.getenv("REDIS_DB", 0))

    # Slack App Token
    SLACK_APP_TOKEN: Final[str] = os.getenv('SLACK_APP_TOKEN', "")
    SLACK_BOT_TEST_MODE: Final[bool] = os.getenv('SLACK_BOT_TEST_MODE', "False").lower() in ('true', '1', 'yes', 'on')

    # 채널 ID
    HOT_AUTO_DEPOSIT_CHANNEL_ID: Final[str] = os.getenv('HOT_AUTO_DEPOSIT_CHANNEL_ID', "C025V0PJZ1P")
    SNS_TOOL_DEPOSIT_CHANNEL_ID: Final[str] = os.getenv('SNS_TOOL_DEPOSIT_CHANNEL_ID', "C08CHA1TZQW")
    MONEYCOON_DEPOSIT_CHANNEL_ID: Final[str] = os.getenv('MONEYCOON_DEPOSIT_CHANNEL_ID', "C0376RS8KLZ")
    JAPAN_NIHON_DEPOSIT_CHANNEL_ID: Final[str] = os.getenv('JAPAN_NIHON_DEPOSIT_CHANNEL_ID', "C05LS9VF5DY")
    JAPAN_TOMO_DEPOSIT_CHANNEL_ID: Final[str] = os.getenv('JAPAN_TOMO_DEPOSIT_CHANNEL_ID', "C06C3HG1Q0K")
    JAPAN_FOLLOWERLAB_DEPOSIT_CHANNEL_ID: Final[str] = os.getenv('JAPAN_FOLLOWERLAB_DEPOSIT_CHANNEL_ID', "C08F10YTBKK")
    SERVICE_TEAM_HOT_PARTNERS_DEPOSIT_CHANNEL_ID: Final[str] = os.getenv('SERVICE_TEAM_HOT_PARTNERS_DEPOSIT_CHANNEL_ID', "C08BR1P920H")
    SERVICE_TEAM_SMS_CHANNEL_ID: Final[str] = os.getenv('SERVICE_TEAM_SMS_CHANNEL_ID', "C05NYEWHK1S")

    CHANNEL_IDS: Final[dict[str, str]] = {
        "HOT_AUTO": HOT_AUTO_DEPOSIT_CHANNEL_ID,
        "SNS_TOOL": SNS_TOOL_DEPOSIT_CHANNEL_ID,
        "MONEYCOON": MONEYCOON_DEPOSIT_CHANNEL_ID,
        "JAPAN_NIHON": JAPAN_NIHON_DEPOSIT_CHANNEL_ID,
        "JAPAN_TOMO": JAPAN_TOMO_DEPOSIT_CHANNEL_ID,
        "JAPAN_FOLLOWERLAB": JAPAN_FOLLOWERLAB_DEPOSIT_CHANNEL_ID,
        "SERVICE_TEAM_HOT_PARTNERS": SERVICE_TEAM_HOT_PARTNERS_DEPOSIT_CHANNEL_ID,
        "SERVICE_TEAM_SMS": SERVICE_TEAM_SMS_CHANNEL_ID,
    }

    # 일본
    JAPAN_NIHON_EMAIL: Final[str] = os.getenv('JAPAN_NIHON_EMAIL', "")
    JAPAN_TOMO: Final[str] = os.getenv('JAPAN_TOMO', "")

    JAPAN_CHANNELS: Final[list[str]] = [
        JAPAN_NIHON_DEPOSIT_CHANNEL_ID,
        JAPAN_TOMO_DEPOSIT_CHANNEL_ID,
        JAPAN_FOLLOWERLAB_DEPOSIT_CHANNEL_ID,
    ]
    JAPAN_MAPPING_INFO: Final[dict[str, str]] = {
        JAPAN_NIHON_DEPOSIT_CHANNEL_ID: JAPAN_NIHON_EMAIL,
        JAPAN_TOMO_DEPOSIT_CHANNEL_ID: JAPAN_TOMO,
        JAPAN_FOLLOWERLAB_DEPOSIT_CHANNEL_ID: JAPAN_TOMO,
    }

    # API URL
    HOT_AUTO_API_URL: Final[str] = os.getenv('HOT_AUTO_API_URL', "")
    SNS_TOOL_API_URL: Final[str] = os.getenv('SNS_TOOL_API_URL', "")
    SELF_MARKETING_PLATFORM_API_URL: Final[str] = os.getenv('SELF_MARKETING_PLATFORM_API_URL', "")
    HOT_PARTNERS_API_URL: Final[str] = os.getenv('HOT_PARTNERS_API_URL', "")

    # API 매핑
    API_ENDPOINTS: Final[dict[str, str]] = {
        HOT_AUTO_DEPOSIT_CHANNEL_ID: HOT_AUTO_API_URL,
        SNS_TOOL_DEPOSIT_CHANNEL_ID: SNS_TOOL_API_URL,
        JAPAN_NIHON_DEPOSIT_CHANNEL_ID: SELF_MARKETING_PLATFORM_API_URL,
        JAPAN_TOMO_DEPOSIT_CHANNEL_ID: SELF_MARKETING_PLATFORM_API_URL,
        JAPAN_FOLLOWERLAB_DEPOSIT_CHANNEL_ID: SELF_MARKETING_PLATFORM_API_URL,
        SERVICE_TEAM_SMS_CHANNEL_ID: SELF_MARKETING_PLATFORM_API_URL,
        SERVICE_TEAM_HOT_PARTNERS_DEPOSIT_CHANNEL_ID: HOT_PARTNERS_API_URL,
    }

    # API 인증 키들
    # SNSTOOL_API_KEY = os.getenv('SNSTOOL_API_KEY', '')

config = Config()

